; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:ATmega328PB]
platform = atmelavr
board = ATmega328PB
framework = arduino
board_build.f_cpu = 16000000L
lib_deps =
  adafruit/Adafruit NeoPixel@^1.12.5
  ArcadeProtocol=symlink://../protocol
build_flags =
  -Wall
  -Wextra
  -Werror=return-type
  -D ARCADE_FIRMWARE_VERSION=\"0.1.0\"
monitor_speed = 38400

[env:bringup_ascii]
extends = env:ATmega328PB
build_flags =
  ${env:ATmega328PB.build_flags}
  -D ARCADE_STANDALONE_ASCII_DEBUG=1

[env:fuses_isp]
extends = env:ATmega328PB
board_hardware.oscillator = external
board_bootloader.type = no_bootloader
board_hardware.bod = 2.7v
board_hardware.eesave = yes
upload_protocol = usbasp
upload_flags = -B8

[env:fuses_bootloader]
extends = env:ATmega328PB
board_hardware.oscillator = external
board_bootloader.type = urboot
board_bootloader.speed = 115200
board_hardware.uart = uart0
board_hardware.bod = 2.7v
board_hardware.eesave = yes
upload_protocol = usbasp
upload_flags = -B8
